// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9VFb3EYDeJEgcVNy7ryxlnh6ZB0_YLmo',
    appId: '1:591749575754:web:3756843ae0a360ac3862b3',
    messagingSenderId: '591749575754',
    projectId: 'bblind-date',
    authDomain: 'bblind-date.firebaseapp.com',
    storageBucket: 'bblind-date.appspot.com',
    measurementId: 'G-93N8NFMGYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWB4uBmRQ5ihspOp_QM6ZbHo8b_yPwlWY',
    appId: '1:591749575754:android:b45cccbf6992de833862b3',
    messagingSenderId: '591749575754',
    projectId: 'bblind-date',
    storageBucket: 'bblind-date.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXMhjg3_yN9qRHim7fpNOTryHQkoyQXM0',
    appId: '1:591749575754:ios:ba457e9cd96630ae3862b3',
    messagingSenderId: '591749575754',
    projectId: 'bblind-date',
    storageBucket: 'bblind-date.appspot.com',
    iosBundleId: 'com.leeblinddate.blindDate',
  );
}
